- JOB: intercept -g $DEVNODE | /etc/nixos/home-manager/config/sway/scripts/keybinds/build/caps2esc | uinput -d $DEVNODE
  DEVICE:
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_ESC, BTN_BACK, BTN_RIGHT]
